kind: pipeline
name: meshviewer build

clone:
  depth: 50

# steps:
# - name: clone git
#   image: docker:git
#   commands:
#   - git submodule update --recursive --init

- name: build on node 12
  image: node:12.12.0-stretch
  commands:
  - node --version
  - npm --version
  - yarn --version
  - pwd
  - ls -alh
  - npm i gulp-cli -g
  - yarn
  - gulp

# - name: backup-old-firmware
#   image: appleboy/drone-ssh
#   settings:
#     host: 46.4.138.183
#     username: fwupload
#     key:
#       from_secret: ssh-update
#     port: 22
#     command_timeout: 120m
#     script:
#       - ./rsync-backup.sh
#       - rm -rf /srv/fwuploads/troisdorf/*

