kind: pipeline
name: meshviewer build

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: thunderstorm99/meshviewer
    target: meshviewer
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

